/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/boston.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/boston.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.002']} position={[1.281, 1.378, -0.061]} rotation={[0, -Math.PI / 4, 0]} scale={1.206} />
    </group>
  )
}

useGLTF.preload('/boston.gltf')
