/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/cubes.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cubes.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.002']} position={[-0.541, 1.389, -1.874]} rotation={[0, -Math.PI / 4, 0]} scale={1.206} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.002']} position={[-2.35, 0.752, -0.072]} rotation={[-Math.PI, Math.PI / 4, -Math.PI]} scale={[-1.206, -0.144, -1.206]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.002']} position={[1.281, 1.378, -0.061]} rotation={[0, -Math.PI / 4, 0]} scale={1.206} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.002']} position={[-0.547, 1.38, 1.724]} rotation={[0, -Math.PI / 4, 0]} scale={1.206} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.003']} position={[-0.802, 0.006, -0.48]} rotation={[0, -Math.PI / 4, 0]} scale={[3.211, 0.234, 3.055]} />
    </group>
  )
}

useGLTF.preload('/cubes.gltf')
