/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/base.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Base(props) {
  const { nodes, materials } = useGLTF('models/base.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.003']} position={[-0.802, 0.006, -0.48]} rotation={[0, -Math.PI / 4, 0]} scale={[3.211, 0.234, 3.055]} castShadow receiveShadow />
    </group>
  )
}

useGLTF.preload('models/base.gltf')