/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/london.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function London(props) {
  const { nodes, materials } = useGLTF('models/london.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.002']} position={[-0.547, 1.38, 1.724]} rotation={[0, -Math.PI / 4, 0]} scale={1.206} castShadow receiveShadow/>
    </group>
  )
}

useGLTF.preload('models/london.gltf')