import { editable as e} from "@theatre/r3f";
import React, { useEffect, useMemo, useState, useRef, useCallback, memo } from "react";
import { getProject, val, types } from "@theatre/core";
import fonts from "./fonts";
import { Text } from "@react-three/drei";



export const TextElements = ({ mouseOverEvent, mouseOutEvent }) => {
    
    const [styles, setStyles] = useState({
        maxWidth: 300,
        lineHeight: 1,
        letterSpacing: 0.05,
        textAlign: "center",
        materialType: "MeshStandardMaterial",
      });
    
    const [title, setTitle] = useState({
        fontSize: 0.1,
        font: fonts.SFCompactSemibold,
      });

      const [subtitle, setSubtitle] = useState({
        fontSize: 0.07,
        font: fonts.SFCompactThin,
      });

      const [number, setNumber] = useState({
        fontSize: 0.3,
        font: fonts.SFCompactThin,
      });


    const textElements = [
        {
            key: "P0Text1",
            text: "HI I'M",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: title,
        },
        {
            key: "P0Text2",
            text: "MAGGIE CHAO",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: null,
            closeHover: null,
            props: title,
        },
        {
            key: "P0Text3",
            text: ", A CREATIVE DEVELOPER AND COMPUTATIONAL DESIGNER.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: title,
        },
        {
            key: "P0Text4",
            text: "Scroll to explore my world",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: subtitle,
        },
        {
            key: "P1Text1",
            text: "MY JOURNEY STARTED IN",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: subtitle,
        },
        {
            key: "P1Text2",
            text: "COLORADO",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: null,
            closeHover: null,
            props: title,
        },
        {
            key: "P1Text3",
            text: ", WHERE I GREW UP FASCINATED WITH DESIGN.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: title,
        },
        {
            key: "P1Text4",
            text: "Ever since a young age, I've been passionate about human computer interaction and innovation.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: subtitle,
        },
        {
            key: "P2Text1",
            text: "I MOVED TO",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: title,
        },
        {
            key: "P2Text2",
            text: "BANGKOK, THAILAND",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: null,
            closeHover: null,
            props: title,
        },
        {
            key: "P2Text3",
            text: "WHEN I WAS 16.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: title,
        },
        {
            key: "P2Text4",
            text: "Since then, I've picked up",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: subtitle,
        },
        {
            key: "P2Text5",
            text: "these skills",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: subtitle,
        },
        {
            key: "P2Text6",
            text: "in design, computation, and fabrication.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: null,
            closeHover: null,
            props: subtitle,
        },
        {
            key: "P3Text1",
            text: "01.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: number,
        },
        {
            key: "P3Text2",
            text: "WHILE STUDYING ARCHITECTURE IN",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P3Text3",
            text: "LONDON",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P3Text4",
            text: "AT UCL, I CREATED AN AUGMENTED REALITY MEMORY PALACE CALLED",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P3Text5",
            text: "INTRODUCING ECHO",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P4Text1",
            text: "02.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: number,
        },
        {
            key: "P4Text2",
            text: "IN LONDON, I CREATED EXPRESSIVE UX/UI DESIGNS FOR HIGH FASHION BRAND,",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P4Text3",
            text: "NOSAKHARI",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P5Text1",
            text: "03.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: number,
        },
        {
            key: "P5Text2",
            text: "DURING MY GRADUATE STUDIES IN",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P5Text3",
            text: "BOSTON",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P5Text4",
            text: ", I CREATED A TEXT TO FACADE AI MODEL CALLED",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P5Text5",
            text: "DEEPFACADE",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P5Text6",
            text: "FOR A PROJECT AT",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P5Text7",
            text: "MIT.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P6Text1",
            text: "04.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: number,
        },
        {
            key: "P6Text2",
            text: "AT",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P6Text3",
            text: "HARVARD GSD",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P6Text4",
            text: ", I GAMIFIED SHOPPING REWARDS USING AUGMENTED REALITY IN THE PROJECT",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P6Text5",
            text: "TEMPLES OF CONSUMERISM.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P7Text1",
            text: "05.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: number,
        },
        {
            key: "P7Text2",
            text: "IN COLLABORATION WITH THE",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P7Text3",
            text: "MAP+S LAB",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P7Text4",
            text: ", I BUILT AN TREND PREDICTING AI MODEL THROUGH",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P7Text5",
            text: "MACHINE LEARNING RESEARCH.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P8Text1",
            text: "EXPLORE MY OTHER PROJECTS ON",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P8Text2",
            text: "COMPUTATION, UX/UI,",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P8Text3",
            text: "AND",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P8Text4",
            text: "FABRICATION.",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "red",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: title,
        },
        {
            key: "P8Text5",
            text: "Double click to enter",
            fillOpacityState: useState(null),
            ref: useRef(),
            color: "black",
            showHover: mouseOverEvent,
            closeHover: mouseOutEvent,
            props: subtitle,
        },
        ];

      useEffect(() => {
        textElements.forEach((element) => {
          const [opacityState, setOpacityState] = element.fillOpacityState;
    
          if (!opacityState) return;
    
          const unsubscribe = opacityState.onValuesChange((newValues) => {
            element.ref.current.fillOpacity = newValues.fillOpacity;
          });
    
          return unsubscribe;
        });
      }, [textElements]);

    return (
        <>
        {textElements.map((element) => (
        <e.mesh key={element.key} theatreKey={element.key} additionalProps={{ fillOpacity: types.number(1, { nudgeMultiplier: 0.1 }) }} objRef={element.fillOpacityState[1]}>
          <Text ref={element.ref} text={element.text} onPointerOver={element.showHover} onPointerOut={element.closeHover} color={element.color} {...styles} {...element.props}/>
        </e.mesh>
      ))}
        </>
        )
    }
    
    